import fs from "node:fs";

const schema = JSON.parse(fs.readFileSync(new URL("./desktop-api.schema.json", import.meta.url)));
const capabilities = [...schema.capabilities.always, ...schema.capabilities.nativeDesktop]
  .map((name) => `  | ${JSON.stringify(name)}`)
  .join("\n");
const events = Object.entries(schema.events)
  .map(([name, type]) => `  ${JSON.stringify(name)}: ${type};`)
  .join("\n");
const output = `// Generated by generate-schema.mjs. Do not edit.\nexport type AlexCapability =\n${capabilities};\n\nexport interface AlexGeneratedEventMap {\n${events}\n}\n`;
const target = new URL("./schema.generated.d.ts", import.meta.url);
if (process.argv.includes("--check")) {
  if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== output) {
    throw new Error("schema.generated.d.ts is stale; run npm run generate");
  }
} else {
  fs.writeFileSync(target, output);
}
