import fs from "node:fs";

const here = new URL("./", import.meta.url);
const schema = JSON.parse(fs.readFileSync(new URL("desktop-api.schema.json", here)));
const groups = ["always", "nativeDesktop", "experimental"];
const all = groups.flatMap((group) => schema.capabilities[group].map((name) => ({ name, group })));
const duplicates = all.map(x => x.name).filter((name, index, names) => names.indexOf(name) !== index);
if (duplicates.length) throw new Error(`duplicate API methods: ${duplicates.join(", ")}`);
for (const { name } of all) {
  const domain = name.split(".")[0];
  if (!schema.domains[domain]) throw new Error(`method ${name} has no domain metadata`);
  if (!schema.methods?.[name]?.params || !schema.methods?.[name]?.result) {
    throw new Error(`method ${name} has no explicit params/result JSON Schema`);
  }
}
const unknownMethods = Object.keys(schema.methods ?? {}).filter(name => !all.some(method => method.name === name));
if (unknownMethods.length) throw new Error(`schemas exist for unregistered methods: ${unknownMethods.join(", ")}`);

const capabilities = all.filter(x => x.group !== "experimental").map(({ name }) => `  | ${JSON.stringify(name)}`).join("\n");
const events = Object.entries(schema.events).map(([name, type]) => `  ${JSON.stringify(name)}: ${type};`).join("\n");
const schemaType = value => {
  if (!value) return "unknown";
  if (value.anyOf) return value.anyOf.map(schemaType).join(" | ");
  if (value.oneOf) return value.oneOf.map(schemaType).join(" | ");
  if (value.$ref) return value.$ref.split("/").at(-1);
  if (value.const !== undefined) return JSON.stringify(value.const);
  if (value.enum) return value.enum.map(item => JSON.stringify(item)).join(" | ");
  if (Array.isArray(value.type)) return value.type.map(type => schemaType({ ...value, type })).join(" | ");
  if (value.type === "string") return "string";
  if (value.type === "number" || value.type === "integer") return "number";
  if (value.type === "boolean") return "boolean";
  if (value.type === "null") return "null";
  if (value.type === "array") return `Array<${schemaType(value.items)}>`;
  if (value.type === "object" || value.properties) {
    const required = new Set(value.required ?? []);
    const fields = Object.entries(value.properties ?? {}).map(([key, child]) => `${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${schemaType(child)}`);
    if (value.additionalProperties === true) fields.push("[key: string]: unknown");
    else if (value.additionalProperties && typeof value.additionalProperties === "object") fields.push(`[key: string]: ${schemaType(value.additionalProperties)}`);
    return `{ ${fields.join("; ")} }`;
  }
  return "unknown";
};
const definitions = Object.entries(schema.$defs ?? {}).map(([name, value]) => `export type ${name} = ${schemaType(value)};`).join("\n");
const methodMap = all.map(({ name }) => {
  const method = schema.methods?.[name];
  return `  ${JSON.stringify(name)}: { params: ${method ? schemaType(method.params) : "Record<string, unknown>"}; result: ${schemaType(method?.result)} };`;
}).join("\n");
const ts = `// Generated by generate-schema.mjs. Do not edit.\n${definitions}\n\nexport type AlexCapability =\n${capabilities};\n\nexport interface AlexGeneratedEventMap {\n${events}\n}\n\nexport interface AlexMethodMap {\n${methodMap}\n}\nexport type AlexMethodName = keyof AlexMethodMap;\n`;

const rustArray = (name, values) => values.length === 0 ? `pub const ${name}: &[&str] = &[];` : `pub const ${name}: &[&str] = &[\n${values.map(v => `    ${JSON.stringify(v)},`).join("\n")}\n];`;
const descriptors = all.map(({ name, group }) => {
  const domain = name.split(".")[0]; const meta = schema.domains[domain];
  return `    MethodDescriptor {\n        name: ${JSON.stringify(name)},\n        domain: ${JSON.stringify(domain)},\n        availability: ${JSON.stringify(group)},\n        permission: ${JSON.stringify(meta.permission)},\n        execution: ${JSON.stringify(meta.execution)},\n    },`;
}).join("\n");
const rust = `// Generated by packages/sdk/generate-schema.mjs. Do not edit.\n#[derive(Debug, Clone, Copy)]\npub struct MethodDescriptor {\n    pub name: &'static str,\n    pub domain: &'static str,\n    pub availability: &'static str,\n    pub permission: &'static str,\n    pub execution: &'static str,\n}\n${rustArray("ALWAYS", schema.capabilities.always)}\n${rustArray("NATIVE_DESKTOP", schema.capabilities.nativeDesktop)}\n${rustArray("EXPERIMENTAL", schema.capabilities.experimental)}\npub const METHODS: &[MethodDescriptor] = &[\n${descriptors}\n];\n`;

const rows = all.map(({ name, group }) => { const meta = schema.domains[name.split(".")[0]]; return `| \`${name}\` | ${group} | ${meta.permission} | ${meta.execution} |`; }).join("\n");
const typedCount = all.filter(({ name }) => schema.methods?.[name]).length;
const docs = `# Desktop API reference\n\nGenerated from \`packages/sdk/desktop-api.schema.json\`. Do not edit manually.\n\n| Method | Availability | Permission | Execution |\n|---|---|---|---|\n${rows}\n\nTyped JSON Schema coverage: ${typedCount}/${all.length} methods.\n\nCommon errors: ${schema.errors.map(e => `\`${e}\``).join(", ")}.\n`;

const outputs = [
  [new URL("schema.generated.d.ts", here), ts],
  [new URL("../../src/api/idl_generated.rs", here), rust],
  [new URL("../../docs/DESKTOP_API_REFERENCE.md", here), docs],
];
if (process.argv.includes("--check")) {
  for (const [target, output] of outputs) if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== output) throw new Error(`${target.pathname} is stale; run npm run generate`);
} else {
  for (const [target, output] of outputs) fs.writeFileSync(target, output);
}
