import fs from "node:fs";

const here = new URL("./", import.meta.url);
const schema = JSON.parse(fs.readFileSync(new URL("desktop-api.schema.json", here)));
const groups = ["always", "nativeDesktop", "experimental"];
const all = groups.flatMap((group) => schema.capabilities[group].map((name) => ({ name, group })));
const duplicates = all.map(x => x.name).filter((name, index, names) => names.indexOf(name) !== index);
if (duplicates.length) throw new Error(`duplicate API methods: ${duplicates.join(", ")}`);
for (const { name } of all) {
  const domain = name.split(".")[0];
  if (!schema.domains[domain]) throw new Error(`method ${name} has no domain metadata`);
}

const capabilities = all.filter(x => x.group !== "experimental").map(({ name }) => `  | ${JSON.stringify(name)}`).join("\n");
const events = Object.entries(schema.events).map(([name, type]) => `  ${JSON.stringify(name)}: ${type};`).join("\n");
const methodMap = all.map(({ name }) => `  ${JSON.stringify(name)}: { params: Record<string, unknown>; result: unknown };`).join("\n");
const ts = `// Generated by generate-schema.mjs. Do not edit.\nexport type AlexCapability =\n${capabilities};\n\nexport interface AlexGeneratedEventMap {\n${events}\n}\n\nexport interface AlexMethodMap {\n${methodMap}\n}\nexport type AlexMethodName = keyof AlexMethodMap;\n`;

const rustArray = (name, values) => `pub const ${name}: &[&str] = &[\n${values.map(v => `    ${JSON.stringify(v)},`).join("\n")}\n];`;
const descriptors = all.map(({ name, group }) => {
  const domain = name.split(".")[0]; const meta = schema.domains[domain];
  return `    MethodDescriptor { name: ${JSON.stringify(name)}, domain: ${JSON.stringify(domain)}, availability: ${JSON.stringify(group)}, permission: ${JSON.stringify(meta.permission)}, execution: ${JSON.stringify(meta.execution)} },`;
}).join("\n");
const rust = `// Generated by packages/sdk/generate-schema.mjs. Do not edit.\n#[derive(Debug, Clone, Copy)]\npub struct MethodDescriptor { pub name: &'static str, pub domain: &'static str, pub availability: &'static str, pub permission: &'static str, pub execution: &'static str }\n${rustArray("ALWAYS", schema.capabilities.always)}\n${rustArray("NATIVE_DESKTOP", schema.capabilities.nativeDesktop)}\n${rustArray("EXPERIMENTAL", schema.capabilities.experimental)}\npub const METHODS: &[MethodDescriptor] = &[\n${descriptors}\n];\n`;

const rows = all.map(({ name, group }) => { const meta = schema.domains[name.split(".")[0]]; return `| \`${name}\` | ${group} | ${meta.permission} | ${meta.execution} |`; }).join("\n");
const docs = `# Desktop API reference\n\nGenerated from \`packages/sdk/desktop-api.schema.json\`. Do not edit manually.\n\n| Method | Availability | Permission | Execution |\n|---|---|---|---|\n${rows}\n\nCommon errors: ${schema.errors.map(e => `\`${e}\``).join(", ")}.\n`;

const outputs = [
  [new URL("schema.generated.d.ts", here), ts],
  [new URL("../../src/api/idl_generated.rs", here), rust],
  [new URL("../../docs/DESKTOP_API_REFERENCE.md", here), docs],
];
if (process.argv.includes("--check")) {
  for (const [target, output] of outputs) if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== output) throw new Error(`${target.pathname} is stale; run npm run generate`);
} else {
  for (const [target, output] of outputs) fs.writeFileSync(target, output);
}
