// Generated by generate-schema.mjs. Do not edit.
export type Empty = {  };
export type InstanceId = { "instanceId": string };
export type ModelId = { "modelId": string };
export type AgentRunId = { "runId": string };
export type ModelManifest = { "id": string; "digest": string; "sizeBytes": number; "format": string; "architecture": string; "quantization"?: string | null; "license"?: string | null; "source"?: string | null; "compatibleWorkers": Array<string> };
export type ModelDownloadRequest = { "url": string; "manifest": ModelManifest; "publisherKey": string; "signature": string; "acceptLicense"?: boolean };
export type ModelDownloadTask = { "id": string; "request": ModelDownloadRequest; "state": "queued" | "running" | "paused" | "completed" | "failed"; "downloadedBytes": number; "totalBytes": number; "createdAtMs": number; "updatedAtMs": number; "error"?: string | null; "result"?: ModelManifest | null };
export type HardwareProfile = { "logicalCpus": number; "providers": Array<"cpu" | "cuda" | "directMl" | "coreMl" | "rocm">; "devices": Array<{ "id": string; "name": string; "kind": string; "provider": "cpu" | "cuda" | "directMl" | "coreMl" | "rocm"; "memoryMb"?: number | null }> };
export type ModelResourceStatus = { "budget": { "memoryBytes": number; "maxLoadedModels": number; "maxConcurrentRequestsPerModel": number }; "allocatedBytes": number; "models": Array<{ "modelId": string; "worker": string; "memoryBytes": number; "activeRequests": number; "lastUsedMs": number }> };
export type ModelWorkerHealth = { "kind": string; "healthy": boolean; "pid"?: number | null; "error"?: string | null };
export type WorkerPackageManifest = { "schemaVersion": 1; "engine": "llama-cpp" | "onnx-runtime-genai"; "workerKind": "llama-cpp" | "onnxruntime-genai"; "version": string; "triple": string; "url": string; "sha256": string; "sizeBytes": number; "publisherKey": string };
export type InstalledWorkerPackage = { "engine": "llama-cpp" | "onnx-runtime-genai"; "workerKind": string; "version": string; "triple": string; "root": string; "active": boolean };
export type AgentSpec = { "model": string; "systemPrompt"?: string; "tools"?: Array<{ "binding": string; "name": string; "idempotent"?: boolean; "requireApproval"?: boolean; "dependsOn"?: Array<string> }>; "budget"?: { "maxSteps"?: number; "maxTokens"?: number; "maxToolCalls"?: number; "maxWallTimeMs"?: number; "maxContextTokens"?: number; "keepRecentMessages"?: number; "maxCostMicros"?: number; "inputCostMicrosPerMillion"?: number; "outputCostMicrosPerMillion"?: number; "toolCostMicros"?: { [key: string]: number } } };
export type UpdateTask = { "id": string; "appId": string; "manifestUrl": string; "channel": "stable" | "beta" | "dev"; "state": string; "stage": string; "progress": number; "error": string | null };
export type JsonValue = unknown;
export type SecretRef = { "service": string; "account": string };
export type ProviderConfig = { "id": string; "kind": "open-ai-compatible" | "anthropic" | "gemini"; "endpoint": string; "secretRef": SecretRef; "defaultModel"?: string | null; "organization"?: string | null; "timeoutMs"?: number; "maxRetries"?: number; "enabled"?: boolean };
export type PathInput = { "path": string };
export type FileGrant = { "path": string; "token": string; "ops": Array<"read" | "write">; "expiresAt": number };
export type FileStat = { "path": string; "type": "file" | "directory" | "symlink" | "other"; "size": number; "readOnly": boolean; "modifiedMs"?: number | null };
export type DirectoryEntry = { "name": string; "type": "file" | "directory" | "symlink" | "other"; "size": number };
export type WindowInfo = { "id": number; "url": string; "title": string; "width": number; "height": number; "x": number | null; "y": number | null; "fullscreen": boolean };
export type ContainerView = { "instanceId": string; "appId": string; "appVersion": string; "desired": string; "observed": string; "isolationRequested": string; "isolationEffective": string; "pid"?: number | null; "port"?: number | null; "restartCount": number; "generation": number; "createdAt": string; "updatedAt": string; "instanceDir": string };
export type MenuTemplate = { [key: string]: unknown };
export type RuntimeStatus = { [key: string]: unknown };

export type AlexCapability =
  | "filesystem.readText"
  | "filesystem.readBinary"
  | "filesystem.writeText"
  | "filesystem.writeBinary"
  | "filesystem.exists"
  | "filesystem.stat"
  | "filesystem.readDir"
  | "filesystem.createDir"
  | "filesystem.remove"
  | "filesystem.rename"
  | "filesystem.copy"
  | "filesystem.watch"
  | "filesystem.unwatch"
  | "storage.get"
  | "storage.set"
  | "storage.delete"
  | "storage.clear"
  | "storage.keys"
  | "paths.dataDir"
  | "paths.cacheDir"
  | "paths.tempDir"
  | "dialog.openFile"
  | "dialog.openFiles"
  | "dialog.openDirectory"
  | "dialog.saveFile"
  | "clipboard.readText"
  | "clipboard.writeText"
  | "system.info"
  | "system.capabilities"
  | "system.requestPermission"
  | "system.openExternal"
  | "system.listApps"
  | "system.listExtensions"
  | "system.install"
  | "system.uninstall"
  | "system.updateStart"
  | "system.updateTasks"
  | "system.updateCancel"
  | "system.updateRetry"
  | "system.listPermissions"
  | "system.setPermission"
  | "system.listTrustedPublishers"
  | "system.readAuditLog"
  | "window.setTitle"
  | "window.minimize"
  | "window.maximize"
  | "window.close"
  | "notification.show"
  | "runtime.invoke"
  | "runtime.status"
  | "runtime.restart"
  | "runtime.cancel"
  | "stream.credit"
  | "stream.read"
  | "stream.cancel"
  | "mcp.connections"
  | "mcp.health"
  | "mcp.discover"
  | "mcp.listTools"
  | "mcp.callTool"
  | "mcp.callToolInteractive"
  | "mcp.respondInput"
  | "mcp.presentInput"
  | "mcp.oauthBegin"
  | "mcp.oauthLoopback"
  | "mcp.oauthComplete"
  | "mcp.audit"
  | "mcp.listResources"
  | "mcp.readResource"
  | "mcp.listPrompts"
  | "mcp.getPrompt"
  | "mcp.complete"
  | "mcp.ping"
  | "mcp.listen"
  | "model.list"
  | "model.import"
  | "model.downloadStart"
  | "model.downloadList"
  | "model.downloadStatus"
  | "model.downloadPause"
  | "model.downloadResume"
  | "model.hardware"
  | "model.runtimeStatus"
  | "model.workerPackages"
  | "model.workerInstall"
  | "model.workerActivate"
  | "model.remove"
  | "model.load"
  | "model.unload"
  | "model.cancel"
  | "model.generate"
  | "model.embed"
  | "model.providers"
  | "model.providerUpsert"
  | "model.providerRemove"
  | "model.providerHealth"
  | "model.secretSet"
  | "model.secretDelete"
  | "model.secretExists"
  | "agent.create"
  | "agent.spawnChild"
  | "agent.children"
  | "agent.waitChildren"
  | "agent.schedule"
  | "agent.scheduled"
  | "agent.start"
  | "agent.pause"
  | "agent.resume"
  | "agent.cancel"
  | "agent.approve"
  | "agent.deny"
  | "agent.status"
  | "agent.list"
  | "agent.history"
  | "agent.timeline"
  | "events.subscribe"
  | "events.unsubscribe"
  | "system.instances.create"
  | "system.instances.start"
  | "system.instances.stop"
  | "system.instances.restart"
  | "system.instances.remove"
  | "system.instances.inspect"
  | "system.instances.list"
  | "system.instances.logs"
  | "process.spawn"
  | "process.kill"
  | "net.fetch"
  | "window.create"
  | "window.list"
  | "window.getBounds"
  | "window.setBounds"
  | "window.setFullscreen"
  | "window.isFullscreen"
  | "window.destroy"
  | "menu.setApplicationMenu"
  | "menu.setContextMenu"
  | "tray.create"
  | "tray.destroy"
  | "shortcuts.register"
  | "shortcuts.unregister"
  | "shortcuts.list";

export type AlexResourceKind =
  | "none"
  | "file"
  | "storage-entry"
  | "path"
  | "dialog-selection"
  | "clipboard"
  | "host"
  | "window"
  | "menu"
  | "tray"
  | "shortcut"
  | "notification"
  | "runtime"
  | "stream"
  | "mcp-binding"
  | "model"
  | "agent-run"
  | "event-subscription"
  | "process"
  | "network-origin";

export interface AlexMethodSecurityMap {
  "filesystem.readText": { action: "filesystem.readText"; permissions: readonly ["filesystem.read"]; resource: "file"; maturity: "stable" };
  "filesystem.readBinary": { action: "filesystem.readBinary"; permissions: readonly ["filesystem.read"]; resource: "file"; maturity: "stable" };
  "filesystem.writeText": { action: "filesystem.writeText"; permissions: readonly ["filesystem.write"]; resource: "file"; maturity: "stable" };
  "filesystem.writeBinary": { action: "filesystem.writeBinary"; permissions: readonly ["filesystem.write"]; resource: "file"; maturity: "stable" };
  "filesystem.exists": { action: "filesystem.exists"; permissions: readonly ["filesystem.read"]; resource: "file"; maturity: "stable" };
  "filesystem.stat": { action: "filesystem.stat"; permissions: readonly ["filesystem.read"]; resource: "file"; maturity: "stable" };
  "filesystem.readDir": { action: "filesystem.readDir"; permissions: readonly ["filesystem.read"]; resource: "file"; maturity: "stable" };
  "filesystem.createDir": { action: "filesystem.createDir"; permissions: readonly ["filesystem.write"]; resource: "file"; maturity: "stable" };
  "filesystem.remove": { action: "filesystem.remove"; permissions: readonly ["filesystem.delete"]; resource: "file"; maturity: "stable" };
  "filesystem.rename": { action: "filesystem.rename"; permissions: readonly ["filesystem.write", "filesystem.delete"]; resource: "file"; maturity: "stable" };
  "filesystem.copy": { action: "filesystem.copy"; permissions: readonly ["filesystem.read", "filesystem.write"]; resource: "file"; maturity: "stable" };
  "filesystem.watch": { action: "filesystem.watch"; permissions: readonly ["filesystem.watch"]; resource: "file"; maturity: "stable" };
  "filesystem.unwatch": { action: "filesystem.unwatch"; permissions: readonly []; resource: "file"; maturity: "stable" };
  "storage.get": { action: "storage.get"; permissions: readonly ["storage"]; resource: "storage-entry"; maturity: "stable" };
  "storage.set": { action: "storage.set"; permissions: readonly ["storage"]; resource: "storage-entry"; maturity: "stable" };
  "storage.delete": { action: "storage.delete"; permissions: readonly ["storage"]; resource: "storage-entry"; maturity: "stable" };
  "storage.clear": { action: "storage.clear"; permissions: readonly ["storage"]; resource: "storage-entry"; maturity: "stable" };
  "storage.keys": { action: "storage.keys"; permissions: readonly ["storage"]; resource: "storage-entry"; maturity: "stable" };
  "paths.dataDir": { action: "paths.dataDir"; permissions: readonly ["paths"]; resource: "path"; maturity: "stable" };
  "paths.cacheDir": { action: "paths.cacheDir"; permissions: readonly ["paths"]; resource: "path"; maturity: "stable" };
  "paths.tempDir": { action: "paths.tempDir"; permissions: readonly ["paths"]; resource: "path"; maturity: "stable" };
  "dialog.openFile": { action: "dialog.openFile"; permissions: readonly ["dialog.open"]; resource: "dialog-selection"; maturity: "stable" };
  "dialog.openFiles": { action: "dialog.openFiles"; permissions: readonly ["dialog.open"]; resource: "dialog-selection"; maturity: "stable" };
  "dialog.openDirectory": { action: "dialog.openDirectory"; permissions: readonly ["dialog.open"]; resource: "dialog-selection"; maturity: "stable" };
  "dialog.saveFile": { action: "dialog.saveFile"; permissions: readonly ["dialog.save"]; resource: "dialog-selection"; maturity: "stable" };
  "clipboard.readText": { action: "clipboard.readText"; permissions: readonly ["clipboard.read"]; resource: "clipboard"; maturity: "stable" };
  "clipboard.writeText": { action: "clipboard.writeText"; permissions: readonly ["clipboard.write"]; resource: "clipboard"; maturity: "stable" };
  "system.info": { action: "system.info"; permissions: readonly []; resource: "host"; maturity: "stable" };
  "system.capabilities": { action: "system.capabilities"; permissions: readonly []; resource: "host"; maturity: "stable" };
  "system.requestPermission": { action: "system.requestPermission"; permissions: readonly []; resource: "host"; maturity: "stable" };
  "system.openExternal": { action: "system.openExternal"; permissions: readonly ["system.openExternal"]; resource: "host"; maturity: "stable" };
  "system.listApps": { action: "system.listApps"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.listExtensions": { action: "system.listExtensions"; permissions: readonly ["system.manageExtensions"]; resource: "host"; maturity: "stable" };
  "system.install": { action: "system.install"; permissions: readonly ["system.install"]; resource: "host"; maturity: "stable" };
  "system.uninstall": { action: "system.uninstall"; permissions: readonly ["system.uninstall"]; resource: "host"; maturity: "stable" };
  "system.updateStart": { action: "system.updateStart"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.updateTasks": { action: "system.updateTasks"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.updateCancel": { action: "system.updateCancel"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.updateRetry": { action: "system.updateRetry"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.listPermissions": { action: "system.listPermissions"; permissions: readonly ["system.managePermissions"]; resource: "host"; maturity: "stable" };
  "system.setPermission": { action: "system.setPermission"; permissions: readonly ["system.managePermissions"]; resource: "host"; maturity: "stable" };
  "system.listTrustedPublishers": { action: "system.listTrustedPublishers"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.readAuditLog": { action: "system.readAuditLog"; permissions: readonly ["system.managePermissions"]; resource: "host"; maturity: "stable" };
  "window.setTitle": { action: "window.setTitle"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "window.minimize": { action: "window.minimize"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "window.maximize": { action: "window.maximize"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "window.close": { action: "window.close"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "notification.show": { action: "notification.show"; permissions: readonly ["notification.show"]; resource: "notification"; maturity: "stable" };
  "runtime.invoke": { action: "runtime.invoke"; permissions: readonly ["runtime.invoke"]; resource: "runtime"; maturity: "stable" };
  "runtime.status": { action: "runtime.status"; permissions: readonly ["runtime.manage"]; resource: "runtime"; maturity: "stable" };
  "runtime.restart": { action: "runtime.restart"; permissions: readonly ["runtime.manage"]; resource: "runtime"; maturity: "stable" };
  "runtime.cancel": { action: "runtime.cancel"; permissions: readonly ["runtime.invoke"]; resource: "runtime"; maturity: "stable" };
  "stream.credit": { action: "stream.credit"; permissions: readonly ["runtime.invoke"]; resource: "stream"; maturity: "stable" };
  "stream.read": { action: "stream.read"; permissions: readonly ["runtime.invoke"]; resource: "stream"; maturity: "stable" };
  "stream.cancel": { action: "stream.cancel"; permissions: readonly ["runtime.invoke"]; resource: "stream"; maturity: "stable" };
  "mcp.connections": { action: "mcp.connections"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.health": { action: "mcp.health"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.discover": { action: "mcp.discover"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.listTools": { action: "mcp.listTools"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.callTool": { action: "mcp.callTool"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.callToolInteractive": { action: "mcp.callToolInteractive"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.respondInput": { action: "mcp.respondInput"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.presentInput": { action: "mcp.presentInput"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.oauthBegin": { action: "mcp.oauthBegin"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.oauthLoopback": { action: "mcp.oauthLoopback"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.oauthComplete": { action: "mcp.oauthComplete"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.audit": { action: "mcp.audit"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.listResources": { action: "mcp.listResources"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.readResource": { action: "mcp.readResource"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.listPrompts": { action: "mcp.listPrompts"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.getPrompt": { action: "mcp.getPrompt"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.complete": { action: "mcp.complete"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.ping": { action: "mcp.ping"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "mcp.listen": { action: "mcp.listen"; permissions: readonly ["mcp.use"]; resource: "mcp-binding"; maturity: "stable" };
  "model.list": { action: "model.list"; permissions: readonly ["model.use"]; resource: "model"; maturity: "stable" };
  "model.import": { action: "model.import"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.downloadStart": { action: "model.downloadStart"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.downloadList": { action: "model.downloadList"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.downloadStatus": { action: "model.downloadStatus"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.downloadPause": { action: "model.downloadPause"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.downloadResume": { action: "model.downloadResume"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.hardware": { action: "model.hardware"; permissions: readonly ["model.use"]; resource: "model"; maturity: "stable" };
  "model.runtimeStatus": { action: "model.runtimeStatus"; permissions: readonly ["model.use"]; resource: "model"; maturity: "stable" };
  "model.workerPackages": { action: "model.workerPackages"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.workerInstall": { action: "model.workerInstall"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.workerActivate": { action: "model.workerActivate"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.remove": { action: "model.remove"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.load": { action: "model.load"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.unload": { action: "model.unload"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.cancel": { action: "model.cancel"; permissions: readonly ["model.use"]; resource: "model"; maturity: "stable" };
  "model.generate": { action: "model.generate"; permissions: readonly ["model.use"]; resource: "model"; maturity: "stable" };
  "model.embed": { action: "model.embed"; permissions: readonly ["model.use"]; resource: "model"; maturity: "stable" };
  "model.providers": { action: "model.providers"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.providerUpsert": { action: "model.providerUpsert"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.providerRemove": { action: "model.providerRemove"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.providerHealth": { action: "model.providerHealth"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.secretSet": { action: "model.secretSet"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.secretDelete": { action: "model.secretDelete"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "model.secretExists": { action: "model.secretExists"; permissions: readonly ["model.manage"]; resource: "model"; maturity: "stable" };
  "agent.create": { action: "agent.create"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.spawnChild": { action: "agent.spawnChild"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.children": { action: "agent.children"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.waitChildren": { action: "agent.waitChildren"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.schedule": { action: "agent.schedule"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.scheduled": { action: "agent.scheduled"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.start": { action: "agent.start"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.pause": { action: "agent.pause"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.resume": { action: "agent.resume"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.cancel": { action: "agent.cancel"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.approve": { action: "agent.approve"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.deny": { action: "agent.deny"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.status": { action: "agent.status"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.list": { action: "agent.list"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.history": { action: "agent.history"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "agent.timeline": { action: "agent.timeline"; permissions: readonly ["agent.run"]; resource: "agent-run"; maturity: "stable" };
  "events.subscribe": { action: "events.subscribe"; permissions: readonly []; resource: "event-subscription"; maturity: "stable" };
  "events.unsubscribe": { action: "events.unsubscribe"; permissions: readonly []; resource: "event-subscription"; maturity: "stable" };
  "system.instances.create": { action: "system.instances.create"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.instances.start": { action: "system.instances.start"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.instances.stop": { action: "system.instances.stop"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.instances.restart": { action: "system.instances.restart"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.instances.remove": { action: "system.instances.remove"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.instances.inspect": { action: "system.instances.inspect"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.instances.list": { action: "system.instances.list"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "system.instances.logs": { action: "system.instances.logs"; permissions: readonly ["system.manageApps"]; resource: "host"; maturity: "stable" };
  "process.spawn": { action: "process.spawn"; permissions: readonly ["process.spawn"]; resource: "process"; maturity: "stable" };
  "process.kill": { action: "process.kill"; permissions: readonly ["process.spawn"]; resource: "process"; maturity: "stable" };
  "net.fetch": { action: "net.fetch"; permissions: readonly ["network.fetch"]; resource: "network-origin"; maturity: "stable" };
  "window.create": { action: "window.create"; permissions: readonly ["window.open"]; resource: "window"; maturity: "stable" };
  "window.list": { action: "window.list"; permissions: readonly ["window.open"]; resource: "window"; maturity: "stable" };
  "window.getBounds": { action: "window.getBounds"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "window.setBounds": { action: "window.setBounds"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "window.setFullscreen": { action: "window.setFullscreen"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "window.isFullscreen": { action: "window.isFullscreen"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "window.destroy": { action: "window.destroy"; permissions: readonly ["window.manage"]; resource: "window"; maturity: "stable" };
  "menu.setApplicationMenu": { action: "menu.setApplicationMenu"; permissions: readonly ["menu.manage"]; resource: "menu"; maturity: "stable" };
  "menu.setContextMenu": { action: "menu.setContextMenu"; permissions: readonly ["menu.manage"]; resource: "menu"; maturity: "stable" };
  "tray.create": { action: "tray.create"; permissions: readonly ["tray.manage"]; resource: "tray"; maturity: "stable" };
  "tray.destroy": { action: "tray.destroy"; permissions: readonly ["tray.manage"]; resource: "tray"; maturity: "stable" };
  "shortcuts.register": { action: "shortcuts.register"; permissions: readonly ["shortcut.register"]; resource: "shortcut"; maturity: "stable" };
  "shortcuts.unregister": { action: "shortcuts.unregister"; permissions: readonly ["shortcut.register"]; resource: "shortcut"; maturity: "stable" };
  "shortcuts.list": { action: "shortcuts.list"; permissions: readonly ["shortcut.register"]; resource: "shortcut"; maturity: "stable" };
}
export type AlexAction = AlexMethodSecurityMap[keyof AlexMethodSecurityMap]["action"];

export interface AlexGeneratedEventMap {
  "menu.clicked": { id: string };
  "tray.clicked": { id: string };
  "shortcut.triggered": { accelerator: string };
}

export interface AlexMethodMap {
  "filesystem.readText": { params: PathInput; result: { "content": string } };
  "filesystem.readBinary": { params: { "path": string; "accessToken"?: string }; result: { "encoding": "base64"; "data": string } };
  "filesystem.writeText": { params: { "path": string; "content": string }; result: { "written": boolean } };
  "filesystem.writeBinary": { params: { "path": string; "data": string; "accessToken"?: string }; result: { "written": boolean } };
  "filesystem.exists": { params: PathInput; result: { "exists": boolean } };
  "filesystem.stat": { params: PathInput; result: FileStat };
  "filesystem.readDir": { params: PathInput; result: { "entries": Array<DirectoryEntry> } };
  "filesystem.createDir": { params: { "path": string; "recursive"?: boolean }; result: { "created": boolean; "exists"?: boolean } };
  "filesystem.remove": { params: { "path": string; "recursive"?: boolean }; result: { "removed": boolean } };
  "filesystem.rename": { params: { "from": string; "to": string }; result: { "renamed": boolean } };
  "filesystem.copy": { params: { "from": string; "to": string }; result: { "copied": boolean } };
  "filesystem.watch": { params: PathInput; result: { "subscriptionId": string; "path": string } };
  "filesystem.unwatch": { params: { "subscriptionId": string }; result: { "removed": boolean } };
  "storage.get": { params: { "key": string }; result: { "value": JsonValue } };
  "storage.set": { params: { "key": string; "value": JsonValue }; result: { "written": boolean } };
  "storage.delete": { params: { "key": string }; result: { "removed": boolean } };
  "storage.clear": { params: Empty; result: { "cleared": boolean } };
  "storage.keys": { params: Empty; result: { "keys": Array<string> } };
  "paths.dataDir": { params: Empty; result: { "path": string } };
  "paths.cacheDir": { params: Empty; result: { "path": string } };
  "paths.tempDir": { params: Empty; result: { "path": string } };
  "dialog.openFile": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }> }; result: FileGrant | { "path": null; "token": null } };
  "dialog.openFiles": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }> }; result: { "paths": Array<FileGrant> } };
  "dialog.openDirectory": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }> }; result: { "paths": Array<FileGrant> } };
  "dialog.saveFile": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }>; "suggestedName"?: string }; result: FileGrant | { "path": null; "token": null } };
  "clipboard.readText": { params: Empty; result: { "text": string } };
  "clipboard.writeText": { params: { "text": string }; result: { "written": boolean } };
  "system.info": { params: Empty; result: { [key: string]: unknown } };
  "system.capabilities": { params: Empty; result: { "capabilities": Array<string>; "experimental": Array<string>; "platform": { "os": "windows" | "macos" | "linux" | "other"; "atomicReplace": boolean; "processTreeLimits": boolean; "filesystemSandbox": boolean; "networkSandbox": boolean; "oci": boolean } } };
  "system.requestPermission": { params: { "permission": string }; result: { "permission": string; "granted": boolean } };
  "system.openExternal": { params: { "url": string }; result: { "opened": boolean } };
  "system.listApps": { params: Empty; result: { "apps": Array<{ [key: string]: unknown }> } };
  "system.listExtensions": { params: Empty; result: { "extensions": Array<{ [key: string]: unknown }> } };
  "system.install": { params: { "packagePath": string; "requireSignature"?: boolean; "trustedKey"?: string }; result: { "installed": string } };
  "system.uninstall": { params: { "id": string }; result: { "removed": string } };
  "system.updateStart": { params: { "id": string; "manifestUrl": string; "channel"?: "stable" | "beta" | "dev" }; result: UpdateTask };
  "system.updateTasks": { params: Empty; result: { "tasks": Array<UpdateTask> } };
  "system.updateCancel": { params: { "taskId": string }; result: { "cancelled": boolean } };
  "system.updateRetry": { params: { "taskId": string }; result: UpdateTask };
  "system.listPermissions": { params: { "id"?: string }; result: { "permissions": Array<{ [key: string]: unknown }> } };
  "system.setPermission": { params: { "id": string; "permission": string; "decision": "prompt" | "granted" | "denied" }; result: { "updated": boolean } };
  "system.listTrustedPublishers": { params: Empty; result: { "publishers": Array<{ [key: string]: unknown }> } };
  "system.readAuditLog": { params: { "limit"?: number }; result: { "entries": Array<{ [key: string]: unknown }> } };
  "window.setTitle": { params: { "title": string }; result: { "accepted": boolean } };
  "window.minimize": { params: Empty; result: { "accepted": boolean } };
  "window.maximize": { params: Empty; result: { "accepted": boolean } };
  "window.close": { params: Empty; result: { "accepted": boolean } };
  "notification.show": { params: { "title": string; "body": string }; result: { "shown": boolean } };
  "runtime.invoke": { params: { "method": string; "params"?: JsonValue }; result: JsonValue };
  "runtime.status": { params: Empty; result: RuntimeStatus };
  "runtime.restart": { params: Empty; result: RuntimeStatus };
  "runtime.cancel": { params: { "requestId": string }; result: { "cancelled": boolean } };
  "stream.credit": { params: { "streamId": string; "bytes": number }; result: { "streamId": string; "available": number } };
  "stream.read": { params: { "streamId": string; "waitMs"?: number }; result: { "streamId": string; "sequence"?: number; "bytes"?: number; "dataBase64"?: string; "pending"?: boolean; "terminal"?: null | { [key: string]: unknown } } };
  "stream.cancel": { params: { "streamId": string; "reason"?: string }; result: { "streamId": string; "cancelled": boolean } };
  "mcp.connections": { params: Empty; result: Array<{ "application": string; "binding": string; "era": "modern" | "legacy" }> };
  "mcp.health": { params: Empty; result: { "connections": Array<{ "application": string; "binding": string; "state": "healthy" | "degraded" | "unhealthy"; "checkedAtMs": number; "latencyMs": number; "consecutiveFailures": number; "lastError"?: string }> } };
  "mcp.discover": { params: { "binding": string }; result: { "supportedVersions": Array<string>; "capabilities": JsonValue; "instructions"?: string; "ttlMs"?: number; "cacheScope"?: string; "_meta"?: JsonValue } };
  "mcp.listTools": { params: { "binding": string; "cursor"?: string }; result: { "tools": Array<{ "name": string; "description"?: string; "inputSchema": JsonValue }>; "nextCursor": string | null } };
  "mcp.callTool": { params: { "binding": string; "name": string; "arguments"?: JsonValue }; result: { "content": Array<JsonValue>; "isError": boolean; "structuredContent"?: JsonValue } };
  "mcp.callToolInteractive": { params: { "binding": string; "name": string; "arguments"?: JsonValue }; result: { "streamId": string; "binding": string; "tool": string } };
  "mcp.respondInput": { params: { "inputId": string; "response": JsonValue }; result: { "inputId": string; "accepted": boolean } };
  "mcp.presentInput": { params: { "inputId": string; "message": string; "title"?: string }; result: { "inputId": string; "accepted": boolean } };
  "mcp.oauthBegin": { params: { "binding": string; "clientId": string; "redirectUri": string; "scopes"?: Array<string> }; result: { "authorizationUrl": string; "state": string; "expiresInMs": number } };
  "mcp.oauthLoopback": { params: { "binding": string; "clientId": string; "scopes"?: Array<string> }; result: { "authorizationUrl": string; "state": string; "redirectUri": string; "expiresInMs": number } };
  "mcp.oauthComplete": { params: { "state": string; "code": string; "issuer": string }; result: { "application": string; "binding": string; "authorized": boolean } };
  "mcp.audit": { params: { "limit"?: number }; result: { "entries": Array<{ "timestampMs": number; "callId": string; "application": string; "binding": string; "tool": string; "phase": "started" | "finished"; "argumentHash"?: string; "previousHash"?: string; "recordHash"?: string; "outcome"?: "success" | "failure"; "durationMs"?: number; "errorKind"?: string }>; "integrity": { "valid": boolean; "checkedRecords": number; "damagedLine"?: number; "reason"?: string } } };
  "mcp.listResources": { params: { "binding": string; "cursor"?: string }; result: { "resources": Array<JsonValue>; "nextCursor"?: string | null; "ttlMs"?: number; "cacheScope"?: string; [key: string]: unknown } };
  "mcp.readResource": { params: { "binding": string; "uri": string }; result: { "contents": Array<JsonValue>; "ttlMs"?: number; "cacheScope"?: string; [key: string]: unknown } };
  "mcp.listPrompts": { params: { "binding": string; "cursor"?: string }; result: { "prompts": Array<JsonValue>; "nextCursor"?: string | null; "ttlMs"?: number; "cacheScope"?: string; [key: string]: unknown } };
  "mcp.getPrompt": { params: { "binding": string; "name": string; "arguments"?: JsonValue }; result: { "description"?: string; "messages": Array<JsonValue>; "ttlMs"?: number; "cacheScope"?: string; [key: string]: unknown } };
  "mcp.complete": { params: { "binding": string; "reference": JsonValue; "argument": JsonValue }; result: JsonValue };
  "mcp.ping": { params: { "binding": string }; result: { "ok": boolean } };
  "mcp.listen": { params: { "binding": string; "filter": { "toolsListChanged"?: boolean; "promptsListChanged"?: boolean; "resourcesListChanged"?: boolean; "resourceSubscriptions"?: Array<string> } }; result: { "streamId": string; "binding": string } };
  "model.list": { params: Empty; result: { "models": Array<ModelManifest> } };
  "model.import": { params: { "source": string; "manifest": ModelManifest }; result: ModelManifest };
  "model.downloadStart": { params: ModelDownloadRequest; result: ModelDownloadTask };
  "model.downloadList": { params: Empty; result: { "tasks": Array<ModelDownloadTask> } };
  "model.downloadStatus": { params: { "taskId": string }; result: ModelDownloadTask };
  "model.downloadPause": { params: { "taskId": string }; result: { "taskId": string; "paused": boolean } };
  "model.downloadResume": { params: { "taskId": string }; result: ModelDownloadTask };
  "model.hardware": { params: Empty; result: HardwareProfile };
  "model.runtimeStatus": { params: Empty; result: { "hardware": HardwareProfile; "resources": ModelResourceStatus; "workers": Array<ModelWorkerHealth> } };
  "model.workerPackages": { params: Empty; result: { "packages": Array<InstalledWorkerPackage> } };
  "model.workerInstall": { params: { "manifest": WorkerPackageManifest; "signature": string }; result: InstalledWorkerPackage };
  "model.workerActivate": { params: { "kind": string; "version": string; "triple": string }; result: { "kind": string; "version": string; "triple": string; "active": boolean } };
  "model.remove": { params: ModelId; result: { "modelId": string; "removed": boolean } };
  "model.load": { params: { "modelId": string; "worker": string }; result: { "modelId": string; "worker": string; "loaded": boolean } };
  "model.unload": { params: ModelId; result: { "modelId": string; "unloaded": boolean } };
  "model.cancel": { params: { "modelId": string; "requestId": string }; result: { "modelId": string; "requestId": string; "cancelled": boolean } };
  "model.generate": { params: { "model": string; "messages": Array<JsonValue>; "options"?: JsonValue }; result: { "streamId": string; "requestId": string } };
  "model.embed": { params: { "model": string; "input": Array<string>; "options"?: JsonValue }; result: JsonValue };
  "model.providers": { params: Empty; result: { "providers": Array<ProviderConfig> } };
  "model.providerUpsert": { params: { "config": ProviderConfig }; result: ProviderConfig };
  "model.providerRemove": { params: { "providerId": string }; result: { "providerId": string; "removed": boolean } };
  "model.providerHealth": { params: { "providerId"?: string }; result: { "providers": Array<JsonValue> } };
  "model.secretSet": { params: { "service": string; "account": string; "secret": string }; result: { "configured": boolean } };
  "model.secretDelete": { params: SecretRef; result: { "deleted": boolean } };
  "model.secretExists": { params: SecretRef; result: { "exists": boolean } };
  "agent.create": { params: { "spec": AgentSpec; "messages"?: Array<JsonValue> }; result: JsonValue };
  "agent.spawnChild": { params: { "parentRunId": string; "spec": AgentSpec; "messages"?: Array<JsonValue> }; result: JsonValue };
  "agent.children": { params: AgentRunId; result: { "runs": Array<JsonValue> } };
  "agent.waitChildren": { params: { "parentRunId": string; "waitMs"?: number; "cancelOnTimeout"?: boolean }; result: JsonValue };
  "agent.schedule": { params: { "runId": string; "scheduledAtMs": number }; result: JsonValue };
  "agent.scheduled": { params: Empty; result: { "runs": Array<JsonValue> } };
  "agent.start": { params: AgentRunId; result: { "runId": string; "streamId": string } };
  "agent.pause": { params: AgentRunId; result: JsonValue };
  "agent.resume": { params: AgentRunId; result: JsonValue };
  "agent.cancel": { params: AgentRunId; result: JsonValue };
  "agent.approve": { params: AgentRunId; result: JsonValue };
  "agent.deny": { params: AgentRunId; result: JsonValue };
  "agent.status": { params: AgentRunId; result: JsonValue };
  "agent.list": { params: Empty; result: { "runs": Array<JsonValue> } };
  "agent.history": { params: { "runId": string; "limit"?: number }; result: { "events": Array<JsonValue> } };
  "agent.timeline": { params: { "runId": string; "limit"?: number }; result: { "entries": Array<JsonValue> } };
  "events.subscribe": { params: { "event": string; "filter"?: { [key: string]: unknown } }; result: { "subscriptionId": string; "event": string } };
  "events.unsubscribe": { params: { "subscriptionId": string }; result: { "removed": boolean } };
  "system.instances.create": { params: { "appId": string; "appVersion": string; "instanceId"?: string; "isolation"?: "process" | "job" | "appcontainer" | "wsl-oci" }; result: ContainerView };
  "system.instances.start": { params: InstanceId; result: ContainerView };
  "system.instances.stop": { params: { "instanceId": string; "timeoutMs"?: number }; result: ContainerView };
  "system.instances.restart": { params: InstanceId; result: ContainerView };
  "system.instances.remove": { params: { "instanceId": string; "deleteData"?: boolean }; result: { "removed": true } };
  "system.instances.inspect": { params: InstanceId; result: ContainerView };
  "system.instances.list": { params: { "appId"?: string; "observed"?: Array<string>; "terminal"?: boolean }; result: { "containers": Array<ContainerView> } };
  "system.instances.logs": { params: { "instanceId": string; "tail"?: number }; result: { "entries": Array<{  }> } };
  "process.spawn": { params: { "executable": string; "args"?: Array<string>; "cwd"?: string; "timeoutMs"?: number }; result: { "pid": string } };
  "process.kill": { params: { "pid": string }; result: { "killed": boolean } };
  "net.fetch": { params: { "url": string; "method"?: string; "headers"?: { [key: string]: string }; "body"?: string; "timeoutMs"?: number; "maxBytes"?: number }; result: { "status": number; "url": string; "headers": Array<{ "name": string; "value": string }>; "bodyEncoding": "base64"; "body": string; "truncated": false } };
  "window.create": { params: { "url": string; "title"?: string; "width"?: number; "height"?: number; "x"?: number; "y"?: number }; result: WindowInfo };
  "window.list": { params: Empty; result: { "windows": Array<WindowInfo> } };
  "window.getBounds": { params: { "windowId": number }; result: { "windowId": number; "x": number | null; "y": number | null; "width": number; "height": number } };
  "window.setBounds": { params: { "windowId": number; "x"?: number; "y"?: number; "width"?: number; "height"?: number }; result: WindowInfo };
  "window.setFullscreen": { params: { "windowId": number; "fullscreen": boolean }; result: WindowInfo };
  "window.isFullscreen": { params: { "windowId": number }; result: { "fullscreen": boolean } };
  "window.destroy": { params: { "windowId": number }; result: { "destroyed": boolean } };
  "menu.setApplicationMenu": { params: MenuTemplate; result: { "applied": boolean } };
  "menu.setContextMenu": { params: MenuTemplate; result: { "applied": boolean } };
  "tray.create": { params: { [key: string]: unknown }; result: { [key: string]: unknown } };
  "tray.destroy": { params: { "id": string }; result: { "destroyed": boolean } };
  "shortcuts.register": { params: { "accelerator": string }; result: { "registered": boolean } };
  "shortcuts.unregister": { params: { "accelerator": string }; result: { "unregistered": boolean } };
  "shortcuts.list": { params: Empty; result: { "shortcuts": Array<string> } };
}
export type AlexMethodName = keyof AlexMethodMap;
