// Generated by generate-schema.mjs. Do not edit.
export type Empty = {  };
export type InstanceId = { "instanceId": string };
export type UpdateTask = { "id": string; "appId": string; "manifestUrl": string; "channel": "stable" | "beta" | "dev"; "state": string; "stage": string; "progress": number; "error": string | null };
export type JsonValue = unknown;
export type PathInput = { "path": string };
export type FileGrant = { "path": string; "token": string; "ops": Array<"read" | "write">; "expiresAt": number };
export type FileStat = { "path": string; "type": "file" | "directory" | "symlink" | "other"; "size": number; "readOnly": boolean; "modifiedMs"?: number | null };
export type DirectoryEntry = { "name": string; "type": "file" | "directory" | "symlink" | "other"; "size": number };
export type WindowInfo = { "id": number; "url": string; "title": string; "width": number; "height": number; "x": number | null; "y": number | null; "fullscreen": boolean };
export type ContainerView = { "instanceId": string; "appId": string; "appVersion": string; "desired": string; "observed": string; "isolationRequested": string; "isolationEffective": string; "pid"?: number | null; "port"?: number | null; "restartCount": number; "generation": number; "createdAt": string; "updatedAt": string; "instanceDir": string };
export type MenuTemplate = { [key: string]: unknown };
export type RuntimeStatus = { [key: string]: unknown };

export type AlexCapability =
  | "filesystem.readText"
  | "filesystem.readBinary"
  | "filesystem.writeText"
  | "filesystem.writeBinary"
  | "filesystem.exists"
  | "filesystem.stat"
  | "filesystem.readDir"
  | "filesystem.createDir"
  | "filesystem.remove"
  | "filesystem.rename"
  | "filesystem.copy"
  | "filesystem.watch"
  | "filesystem.unwatch"
  | "storage.get"
  | "storage.set"
  | "storage.delete"
  | "storage.clear"
  | "storage.keys"
  | "paths.dataDir"
  | "paths.cacheDir"
  | "paths.tempDir"
  | "dialog.openFile"
  | "dialog.openFiles"
  | "dialog.openDirectory"
  | "dialog.saveFile"
  | "clipboard.readText"
  | "clipboard.writeText"
  | "system.info"
  | "system.capabilities"
  | "system.requestPermission"
  | "system.openExternal"
  | "system.listApps"
  | "system.listExtensions"
  | "system.install"
  | "system.uninstall"
  | "system.updateStart"
  | "system.updateTasks"
  | "system.updateCancel"
  | "system.updateRetry"
  | "system.listPermissions"
  | "system.setPermission"
  | "system.listTrustedPublishers"
  | "system.readAuditLog"
  | "window.setTitle"
  | "window.minimize"
  | "window.maximize"
  | "window.close"
  | "notification.show"
  | "runtime.invoke"
  | "runtime.status"
  | "runtime.restart"
  | "runtime.cancel"
  | "events.subscribe"
  | "events.unsubscribe"
  | "system.instances.create"
  | "system.instances.start"
  | "system.instances.stop"
  | "system.instances.restart"
  | "system.instances.remove"
  | "system.instances.inspect"
  | "system.instances.list"
  | "system.instances.logs"
  | "process.spawn"
  | "process.kill"
  | "net.fetch"
  | "window.create"
  | "window.list"
  | "window.getBounds"
  | "window.setBounds"
  | "window.setFullscreen"
  | "window.isFullscreen"
  | "window.destroy"
  | "menu.setApplicationMenu"
  | "menu.setContextMenu"
  | "tray.create"
  | "tray.destroy"
  | "shortcuts.register"
  | "shortcuts.unregister"
  | "shortcuts.list";

export interface AlexGeneratedEventMap {
  "menu.clicked": { id: string };
  "tray.clicked": { id: string };
  "shortcut.triggered": { accelerator: string };
}

export interface AlexMethodMap {
  "filesystem.readText": { params: PathInput; result: { "content": string } };
  "filesystem.readBinary": { params: { "path": string; "accessToken"?: string }; result: { "encoding": "base64"; "data": string } };
  "filesystem.writeText": { params: { "path": string; "content": string }; result: { "written": boolean } };
  "filesystem.writeBinary": { params: { "path": string; "data": string; "accessToken"?: string }; result: { "written": boolean } };
  "filesystem.exists": { params: PathInput; result: { "exists": boolean } };
  "filesystem.stat": { params: PathInput; result: FileStat };
  "filesystem.readDir": { params: PathInput; result: { "entries": Array<DirectoryEntry> } };
  "filesystem.createDir": { params: { "path": string; "recursive"?: boolean }; result: { "created": boolean; "exists"?: boolean } };
  "filesystem.remove": { params: { "path": string; "recursive"?: boolean }; result: { "removed": boolean } };
  "filesystem.rename": { params: { "from": string; "to": string }; result: { "renamed": boolean } };
  "filesystem.copy": { params: { "from": string; "to": string }; result: { "copied": boolean } };
  "filesystem.watch": { params: PathInput; result: { "subscriptionId": string; "path": string } };
  "filesystem.unwatch": { params: { "subscriptionId": string }; result: { "removed": boolean } };
  "storage.get": { params: { "key": string }; result: { "value": JsonValue } };
  "storage.set": { params: { "key": string; "value": JsonValue }; result: { "written": boolean } };
  "storage.delete": { params: { "key": string }; result: { "removed": boolean } };
  "storage.clear": { params: Empty; result: { "cleared": boolean } };
  "storage.keys": { params: Empty; result: { "keys": Array<string> } };
  "paths.dataDir": { params: Empty; result: { "path": string } };
  "paths.cacheDir": { params: Empty; result: { "path": string } };
  "paths.tempDir": { params: Empty; result: { "path": string } };
  "dialog.openFile": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }> }; result: FileGrant | { "path": null; "token": null } };
  "dialog.openFiles": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }> }; result: { "paths": Array<FileGrant> } };
  "dialog.openDirectory": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }> }; result: { "paths": Array<FileGrant> } };
  "dialog.saveFile": { params: { "title"?: string; "defaultPath"?: string; "filters"?: Array<{ "name": string; "extensions": Array<string> }>; "suggestedName"?: string }; result: FileGrant | { "path": null; "token": null } };
  "clipboard.readText": { params: Empty; result: { "text": string } };
  "clipboard.writeText": { params: { "text": string }; result: { "written": boolean } };
  "system.info": { params: Empty; result: { [key: string]: unknown } };
  "system.capabilities": { params: Empty; result: { "capabilities": Array<string>; "experimental": Array<string> } };
  "system.requestPermission": { params: { "permission": string }; result: { "permission": string; "granted": boolean } };
  "system.openExternal": { params: { "url": string }; result: { "opened": boolean } };
  "system.listApps": { params: Empty; result: { "apps": Array<{ [key: string]: unknown }> } };
  "system.listExtensions": { params: Empty; result: { "extensions": Array<{ [key: string]: unknown }> } };
  "system.install": { params: { "packagePath": string; "requireSignature"?: boolean; "trustedKey"?: string }; result: { "installed": string } };
  "system.uninstall": { params: { "id": string }; result: { "removed": string } };
  "system.updateStart": { params: { "id": string; "manifestUrl": string; "channel"?: "stable" | "beta" | "dev" }; result: UpdateTask };
  "system.updateTasks": { params: Empty; result: { "tasks": Array<UpdateTask> } };
  "system.updateCancel": { params: { "taskId": string }; result: { "cancelled": boolean } };
  "system.updateRetry": { params: { "taskId": string }; result: UpdateTask };
  "system.listPermissions": { params: { "id"?: string }; result: { "permissions": Array<{ [key: string]: unknown }> } };
  "system.setPermission": { params: { "id": string; "permission": string; "decision": "prompt" | "granted" | "denied" }; result: { "updated": boolean } };
  "system.listTrustedPublishers": { params: Empty; result: { "publishers": Array<{ [key: string]: unknown }> } };
  "system.readAuditLog": { params: { "limit"?: number }; result: { "entries": Array<{ [key: string]: unknown }> } };
  "window.setTitle": { params: { "title": string }; result: { "accepted": boolean } };
  "window.minimize": { params: Empty; result: { "accepted": boolean } };
  "window.maximize": { params: Empty; result: { "accepted": boolean } };
  "window.close": { params: Empty; result: { "accepted": boolean } };
  "notification.show": { params: { "title": string; "body": string }; result: { "shown": boolean } };
  "runtime.invoke": { params: { "method": string; "params"?: JsonValue }; result: JsonValue };
  "runtime.status": { params: Empty; result: RuntimeStatus };
  "runtime.restart": { params: Empty; result: RuntimeStatus };
  "runtime.cancel": { params: { "requestId": string }; result: { "cancelled": boolean } };
  "events.subscribe": { params: { "event": string; "filter"?: { [key: string]: unknown } }; result: { "subscriptionId": string; "event": string } };
  "events.unsubscribe": { params: { "subscriptionId": string }; result: { "removed": boolean } };
  "system.instances.create": { params: { "appId": string; "appVersion": string; "instanceId"?: string; "isolation"?: "process" | "job" | "appcontainer" | "wsl-oci" }; result: ContainerView };
  "system.instances.start": { params: InstanceId; result: ContainerView };
  "system.instances.stop": { params: { "instanceId": string; "timeoutMs"?: number }; result: ContainerView };
  "system.instances.restart": { params: InstanceId; result: ContainerView };
  "system.instances.remove": { params: { "instanceId": string; "deleteData"?: boolean }; result: { "removed": true } };
  "system.instances.inspect": { params: InstanceId; result: ContainerView };
  "system.instances.list": { params: { "appId"?: string; "observed"?: Array<string>; "terminal"?: boolean }; result: { "containers": Array<ContainerView> } };
  "system.instances.logs": { params: { "instanceId": string; "tail"?: number }; result: { "entries": Array<{  }> } };
  "process.spawn": { params: { "executable": string; "args"?: Array<string>; "cwd"?: string; "timeoutMs"?: number }; result: { "pid": string } };
  "process.kill": { params: { "pid": string }; result: { "killed": boolean } };
  "net.fetch": { params: { "url": string; "method"?: string; "headers"?: { [key: string]: string }; "body"?: string; "timeoutMs"?: number; "maxBytes"?: number }; result: { "status": number; "url": string; "headers": Array<{ "name": string; "value": string }>; "bodyEncoding": "base64"; "body": string; "truncated": false } };
  "window.create": { params: { "url": string; "title"?: string; "width"?: number; "height"?: number; "x"?: number; "y"?: number }; result: WindowInfo };
  "window.list": { params: Empty; result: { "windows": Array<WindowInfo> } };
  "window.getBounds": { params: { "windowId": number }; result: { "windowId": number; "x": number | null; "y": number | null; "width": number; "height": number } };
  "window.setBounds": { params: { "windowId": number; "x"?: number; "y"?: number; "width"?: number; "height"?: number }; result: WindowInfo };
  "window.setFullscreen": { params: { "windowId": number; "fullscreen": boolean }; result: WindowInfo };
  "window.isFullscreen": { params: { "windowId": number }; result: { "fullscreen": boolean } };
  "window.destroy": { params: { "windowId": number }; result: { "destroyed": boolean } };
  "menu.setApplicationMenu": { params: MenuTemplate; result: { "applied": boolean } };
  "menu.setContextMenu": { params: MenuTemplate; result: { "applied": boolean } };
  "tray.create": { params: { [key: string]: unknown }; result: { [key: string]: unknown } };
  "tray.destroy": { params: { "id": string }; result: { "destroyed": boolean } };
  "shortcuts.register": { params: { "accelerator": string }; result: { "registered": boolean } };
  "shortcuts.unregister": { params: { "accelerator": string }; result: { "unregistered": boolean } };
  "shortcuts.list": { params: Empty; result: { "shortcuts": Array<string> } };
}
export type AlexMethodName = keyof AlexMethodMap;
