// Generated by generate-schema.mjs. Do not edit.
export type AlexCapability =
  | "filesystem.readText"
  | "filesystem.readBinary"
  | "filesystem.writeText"
  | "filesystem.writeBinary"
  | "filesystem.exists"
  | "filesystem.stat"
  | "filesystem.readDir"
  | "filesystem.createDir"
  | "filesystem.remove"
  | "filesystem.rename"
  | "filesystem.copy"
  | "filesystem.watch"
  | "filesystem.unwatch"
  | "storage.get"
  | "storage.set"
  | "storage.delete"
  | "storage.clear"
  | "storage.keys"
  | "paths.dataDir"
  | "paths.cacheDir"
  | "paths.tempDir"
  | "dialog.openFile"
  | "dialog.openFiles"
  | "dialog.openDirectory"
  | "dialog.saveFile"
  | "clipboard.readText"
  | "clipboard.writeText"
  | "system.info"
  | "system.capabilities"
  | "system.requestPermission"
  | "system.openExternal"
  | "system.listApps"
  | "system.listExtensions"
  | "system.install"
  | "system.uninstall"
  | "system.updateStart"
  | "system.updateTasks"
  | "system.updateCancel"
  | "system.updateRetry"
  | "system.listPermissions"
  | "system.setPermission"
  | "system.listTrustedPublishers"
  | "system.readAuditLog"
  | "window.setTitle"
  | "window.minimize"
  | "window.maximize"
  | "window.close"
  | "notification.show"
  | "runtime.invoke"
  | "runtime.status"
  | "runtime.restart"
  | "runtime.cancel"
  | "events.subscribe"
  | "events.unsubscribe"
  | "system.container.create"
  | "system.container.start"
  | "system.container.stop"
  | "system.container.restart"
  | "system.container.remove"
  | "system.container.inspect"
  | "system.container.list"
  | "system.container.logs"
  | "process.spawn"
  | "process.kill"
  | "net.fetch"
  | "window.create"
  | "window.list"
  | "window.getBounds"
  | "window.setBounds"
  | "window.setFullscreen"
  | "window.isFullscreen"
  | "window.destroy"
  | "menu.setApplicationMenu"
  | "menu.setContextMenu"
  | "tray.create"
  | "tray.destroy"
  | "shortcuts.register"
  | "shortcuts.unregister"
  | "shortcuts.list";

export interface AlexGeneratedEventMap {
  "menu.clicked": { id: string };
  "tray.clicked": { id: string };
  "shortcut.triggered": { accelerator: string };
}

export interface AlexMethodMap {
  "filesystem.readText": { params: Record<string, unknown>; result: unknown };
  "filesystem.readBinary": { params: Record<string, unknown>; result: unknown };
  "filesystem.writeText": { params: Record<string, unknown>; result: unknown };
  "filesystem.writeBinary": { params: Record<string, unknown>; result: unknown };
  "filesystem.exists": { params: Record<string, unknown>; result: unknown };
  "filesystem.stat": { params: Record<string, unknown>; result: unknown };
  "filesystem.readDir": { params: Record<string, unknown>; result: unknown };
  "filesystem.createDir": { params: Record<string, unknown>; result: unknown };
  "filesystem.remove": { params: Record<string, unknown>; result: unknown };
  "filesystem.rename": { params: Record<string, unknown>; result: unknown };
  "filesystem.copy": { params: Record<string, unknown>; result: unknown };
  "filesystem.watch": { params: Record<string, unknown>; result: unknown };
  "filesystem.unwatch": { params: Record<string, unknown>; result: unknown };
  "storage.get": { params: Record<string, unknown>; result: unknown };
  "storage.set": { params: Record<string, unknown>; result: unknown };
  "storage.delete": { params: Record<string, unknown>; result: unknown };
  "storage.clear": { params: Record<string, unknown>; result: unknown };
  "storage.keys": { params: Record<string, unknown>; result: unknown };
  "paths.dataDir": { params: Record<string, unknown>; result: unknown };
  "paths.cacheDir": { params: Record<string, unknown>; result: unknown };
  "paths.tempDir": { params: Record<string, unknown>; result: unknown };
  "dialog.openFile": { params: Record<string, unknown>; result: unknown };
  "dialog.openFiles": { params: Record<string, unknown>; result: unknown };
  "dialog.openDirectory": { params: Record<string, unknown>; result: unknown };
  "dialog.saveFile": { params: Record<string, unknown>; result: unknown };
  "clipboard.readText": { params: Record<string, unknown>; result: unknown };
  "clipboard.writeText": { params: Record<string, unknown>; result: unknown };
  "system.info": { params: Record<string, unknown>; result: unknown };
  "system.capabilities": { params: Record<string, unknown>; result: unknown };
  "system.requestPermission": { params: Record<string, unknown>; result: unknown };
  "system.openExternal": { params: Record<string, unknown>; result: unknown };
  "system.listApps": { params: Record<string, unknown>; result: unknown };
  "system.listExtensions": { params: Record<string, unknown>; result: unknown };
  "system.install": { params: Record<string, unknown>; result: unknown };
  "system.uninstall": { params: Record<string, unknown>; result: unknown };
  "system.updateStart": { params: Record<string, unknown>; result: unknown };
  "system.updateTasks": { params: Record<string, unknown>; result: unknown };
  "system.updateCancel": { params: Record<string, unknown>; result: unknown };
  "system.updateRetry": { params: Record<string, unknown>; result: unknown };
  "system.listPermissions": { params: Record<string, unknown>; result: unknown };
  "system.setPermission": { params: Record<string, unknown>; result: unknown };
  "system.listTrustedPublishers": { params: Record<string, unknown>; result: unknown };
  "system.readAuditLog": { params: Record<string, unknown>; result: unknown };
  "window.setTitle": { params: Record<string, unknown>; result: unknown };
  "window.minimize": { params: Record<string, unknown>; result: unknown };
  "window.maximize": { params: Record<string, unknown>; result: unknown };
  "window.close": { params: Record<string, unknown>; result: unknown };
  "notification.show": { params: Record<string, unknown>; result: unknown };
  "runtime.invoke": { params: Record<string, unknown>; result: unknown };
  "runtime.status": { params: Record<string, unknown>; result: unknown };
  "runtime.restart": { params: Record<string, unknown>; result: unknown };
  "runtime.cancel": { params: Record<string, unknown>; result: unknown };
  "events.subscribe": { params: Record<string, unknown>; result: unknown };
  "events.unsubscribe": { params: Record<string, unknown>; result: unknown };
  "system.container.create": { params: Record<string, unknown>; result: unknown };
  "system.container.start": { params: Record<string, unknown>; result: unknown };
  "system.container.stop": { params: Record<string, unknown>; result: unknown };
  "system.container.restart": { params: Record<string, unknown>; result: unknown };
  "system.container.remove": { params: Record<string, unknown>; result: unknown };
  "system.container.inspect": { params: Record<string, unknown>; result: unknown };
  "system.container.list": { params: Record<string, unknown>; result: unknown };
  "system.container.logs": { params: Record<string, unknown>; result: unknown };
  "process.spawn": { params: Record<string, unknown>; result: unknown };
  "process.kill": { params: Record<string, unknown>; result: unknown };
  "net.fetch": { params: Record<string, unknown>; result: unknown };
  "window.create": { params: Record<string, unknown>; result: unknown };
  "window.list": { params: Record<string, unknown>; result: unknown };
  "window.getBounds": { params: Record<string, unknown>; result: unknown };
  "window.setBounds": { params: Record<string, unknown>; result: unknown };
  "window.setFullscreen": { params: Record<string, unknown>; result: unknown };
  "window.isFullscreen": { params: Record<string, unknown>; result: unknown };
  "window.destroy": { params: Record<string, unknown>; result: unknown };
  "menu.setApplicationMenu": { params: Record<string, unknown>; result: unknown };
  "menu.setContextMenu": { params: Record<string, unknown>; result: unknown };
  "tray.create": { params: Record<string, unknown>; result: unknown };
  "tray.destroy": { params: Record<string, unknown>; result: unknown };
  "shortcuts.register": { params: Record<string, unknown>; result: unknown };
  "shortcuts.unregister": { params: Record<string, unknown>; result: unknown };
  "shortcuts.list": { params: Record<string, unknown>; result: unknown };
}
export type AlexMethodName = keyof AlexMethodMap;
