//! Method routing only. Domain implementations remain on `ApiRouter`; keeping
//! this table separate makes registration reviewable and prevents the router's
//! lifecycle/validation code from growing with every API method.

use super::{ApiResult, ApiRouter};
use crate::{ipc::Request, native::HostCommand};

pub(super) fn route(router: &ApiRouter, request: &Request, window_id: Option<u64>) -> ApiResult {
    let p = &request.params;
    match request.method.as_str() {
        "filesystem.readText" => router.read_text(p),
        "filesystem.writeText" => router.write_text(p),
        "filesystem.readBinary" => router.read_binary(p),
        "filesystem.writeBinary" => router.write_binary(p),
        "filesystem.exists" => router.fs_exists(p),
        "filesystem.stat" => router.fs_stat(p),
        "filesystem.readDir" => router.fs_read_dir(p),
        "filesystem.createDir" => router.fs_create_dir(p),
        "filesystem.remove" => router.fs_remove(p),
        "filesystem.rename" => router.fs_rename(p),
        "filesystem.copy" => router.fs_copy(p),
        "filesystem.watch" => router.fs_watch(p, window_id),
        "filesystem.unwatch" => router.fs_unwatch(p),
        "storage.get" => router.storage_get(p),
        "storage.set" => router.storage_set(p),
        "storage.delete" => router.storage_delete(p),
        "storage.clear" => router.storage_clear(),
        "storage.keys" => router.storage_keys(),
        "paths.dataDir" => router.paths_data_dir(),
        "paths.cacheDir" => router.paths_cache_dir(),
        "paths.tempDir" => router.paths_temp_dir(),
        "dialog.openFile" => router.dialog_open_file(p, false, false),
        "dialog.openFiles" => router.dialog_open_files(p),
        "dialog.openDirectory" => router.dialog_open_directory(p),
        "dialog.saveFile" => router.dialog_save_file(p),
        "clipboard.readText" => router.clipboard_read_text(),
        "clipboard.writeText" => router.clipboard_write_text(p),
        "system.info" => router.system_info(),
        "system.capabilities" => router.system_capabilities(),
        "system.openExternal" => router.open_external(p),
        "system.requestPermission" => router.request_permission(p),
        "system.install" => router.system_install(p),
        "system.uninstall" => router.system_uninstall(p),
        "system.updateStart" => router.system_update_start(p),
        "system.updateTasks" => router.system_update_tasks(),
        "system.updateCancel" => router.system_update_cancel(p),
        "system.updateRetry" => router.system_update_retry(p),
        "system.listApps" => router.system_list_apps(),
        "system.listExtensions" => router.system_list_extensions(),
        "system.listPermissions" => router.system_list_permissions(p),
        "system.setPermission" => router.system_set_permission(p),
        "system.listTrustedPublishers" => router.system_list_trusted_publishers(),
        "system.readAuditLog" => router.system_read_audit_log(p),
        "system.container.create" => router.system_container_create(p),
        "system.container.start" => router.system_container_start(p),
        "system.container.stop" => router.system_container_stop(p),
        "system.container.restart" => router.system_container_restart(p),
        "system.container.remove" => router.system_container_remove(p),
        "system.container.inspect" => router.system_container_inspect(p),
        "system.container.list" => router.system_container_list(p),
        "system.container.logs" => router.system_container_logs(p),
        "system.instances.create" => router.system_container_create(p),
        "system.instances.start" => router.system_container_start(p),
        "system.instances.stop" => router.system_container_stop(p),
        "system.instances.restart" => router.system_container_restart(p),
        "system.instances.remove" => router.system_container_remove(p),
        "system.instances.inspect" => router.system_container_inspect(p),
        "system.instances.list" => router.system_container_list(p),
        "system.instances.logs" => router.system_container_logs(p),
        "window.setTitle" => router.window_set_title(p),
        "window.minimize" => router.window_command(HostCommand::MinimizeWindow),
        "window.maximize" => router.window_command(HostCommand::MaximizeWindow),
        "window.close" => router.window_command(HostCommand::CloseWindow),
        "window.create" => router.window_create(p),
        "window.list" => router.window_list(),
        "window.getBounds" => router.window_get_bounds(p),
        "window.setBounds" => router.window_set_bounds(p),
        "window.setFullscreen" => router.window_set_fullscreen(p),
        "window.isFullscreen" => router.window_is_fullscreen(p),
        "window.destroy" => router.window_destroy(p),
        "menu.setApplicationMenu" => router.menu_set_application_menu(p),
        "menu.setContextMenu" => router.menu_set_context_menu(p),
        "tray.create" => router.tray_create(p),
        "tray.destroy" => router.tray_destroy(p),
        "shortcuts.register" => router.shortcuts_register(p),
        "shortcuts.unregister" => router.shortcuts_unregister(p),
        "shortcuts.list" => router.shortcuts_list(),
        "notification.show" => router.notification_show(p),
        "runtime.invoke" => router.runtime_invoke(&request.id, p, request.deadline_ms),
        "runtime.status" => router.runtime_status(),
        "runtime.restart" => router.runtime_restart(),
        "runtime.cancel" => router.runtime_cancel(p),
        "stream.credit" => router.stream_credit(p),
        "stream.read" => router.stream_read(p),
        "stream.cancel" => router.stream_cancel(p),
        "events.subscribe" => router.events_subscribe(&request.id, p, window_id),
        "events.unsubscribe" => router.events_unsubscribe(p),
        "process.spawn" => router.process_spawn(p),
        "process.kill" => router.process_kill(p),
        "net.fetch" => router.net_fetch(p),
        _ => Err(("METHOD_NOT_FOUND", "unknown Alex API method".to_owned())),
    }
}
